# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-29 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180401_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.CharField(default='No reply', max_length=800),
            preserve_default=False,
        ),
    ]
